Alfresco/hxinsight-connector

distribution/src/main/resources/docker-compose-origin/.env, distribution/src/main/resources/docker-compose/docker-compose.yml, pom.xml
Update Alfresco Digital Workspace and add Alfresco Control Center in docker compose. Add specific versions to pom. Add tags to .env file.
ACC can be reached via: 
http://localhost:8080/admin
as there is small issue with URL for control center [OPSEXP-2419](https://alfresco.atlassian.net/browse/OPSEXP-2419)
[OPSEXP-2419]: https://alfresco.atlassian.net/browse/OPSEXP-2419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ACS-6432 Update docker compose with ADW and ACC

.github/workflows/ci.yml, README.md, distribution/README.md, distribution/pom.xml, distribution/src/main/resources/docker-compose-origin/.env, distribution/src/main/resources/docker-compose/docker-compose.yml, live-ingester/pom.xml, live-ingester/src/main/resources/application.yml, pom.xml
I have left the references in packages as "hxi", but changed the customer-facing locations to either the full name or "Hx Insight." In particular this will affect the git repository (which will need renaming to "hxinsight-connector") and the S3 release bucket (which will also be updated to "hxinsight-connector").
=> ACS-6550 Use final product name 'Alfresco Connector for Hyland Experience Insight'.

live-ingester/pom.xml
Fix app start-up Camel error `NoClassDefFoundError: org/apache/camel/component/mock/MockComponent`
For more see: https://alfresco.atlassian.net/browse/ACS-6379
=> ACS-6379: Fix app start-up Camel error

live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeMetadataEventSerializer.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/ports/ingestion_engine/UpdateNodeMetadataEvent.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/metadata/IngestMetadataCommandHandler.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeMetadataEventSerializerTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/ports/ingestion_engine/UpdateNodeMetadataEventTest.java
Also fix names of other fields and make UpdateNodeMetadataEventSerializerTest less brittle.
=> ACS-6376 Include objectId in HxInsight call.

bulk-ingester/src/main/java/org/alfresco/hxi_connector/bulk_ingester/processor/mapper/AlfrescoNodeMapper.java, bulk-ingester/src/main/java/org/alfresco/hxi_connector/bulk_ingester/processor/model/Node.java, bulk-ingester/src/test/java/org/alfresco/hxi_connector/bulk_ingester/event/CamelNodePublisherIntegrationTest.java, bulk-ingester/src/test/java/org/alfresco/hxi_connector/bulk_ingester/processor/mapper/AlfrescoNodeMapperTest.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/bulk_ingester/BulkIngesterEventProcessor.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/bulk_ingester/model/BulkIngesterEvent.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/RepoEventMapper.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/property/PropertiesMapper.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/property/PropertyMappingHelper.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/metadata/IngestMetadataCommand.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/metadata/IngestMetadataCommandHandler.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/metadata/model/PredefinedNodeMetadataProperty.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeMetadataEventSerializerTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/bulk_ingester/BulkIngesterEventProcessorTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/RepoEventMapperTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/ports/ingestion_engine/UpdateNodeMetadataEventTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/CreateRequestIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/UpdateRequestIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/metadata/IngestMetadataCommandHandlerTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/metadata/model/PredefinedNodeMetadataPropertyTest.java
Replace unit test for null users in log in event with e2e test, since we've removed the special code to handle this case.
=> ACS-6685 Refactor users into the general properties.

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/RequestFiltersIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/util/ContainerSupport.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/util/E2ETestBase.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/AspectFilterApplier.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/AspectFilterApplierTest.java
This PR fixes aspect filtering logic for a case when not all aspects present on a node are present in allow list (but some are).
That seemed to be a problem with integration test (as the unit test tested the wrong logic but integration test was testing the correct one).
Edit:
I reverted filtering logic. Only changes now are test fixes.
=> ACS-6869: Fixing filter logic.

bulk-ingester/src/main/java/org/alfresco/hxi_connector/bulk_ingester/repository/filter/TypeFilterApplier.java, common/src/main/java/org/alfresco/hxi_connector/common/repository/filter/CollectionFilter.java, common/src/main/java/org/alfresco/hxi_connector/common/repository/filter/FieldFilter.java, common/src/test/java/org/alfresco/hxi_connector/common/repository/filter/CollectionFilterTest.java, common/src/test/java/org/alfresco/hxi_connector/common/repository/filter/FieldFilterTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/RequestFiltersIntegrationTest.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/properties/Filter.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/AncestorFilterApplier.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/AspectFilterApplier.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/TypeFilterApplier.java, live-ingester/src/main/resources/application.yml, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/AncestorFilterApplierTest.java
I assumed that primary path/ancestors will be under same filtering rules as aspects, thus, I've made small generalization for filter utility classes.
=> ACS-6874: Adding primary path/ancestor node filtering in live ingester.

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/CreateRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/RequestFiltersIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/util/ContainerSupport.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializer.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializerTest.java
[HxI LI Integration] Ingestion event handler should return field values only as non-empty strings
https://hyland.atlassian.net/browse/ACS-7473
=> ACS-7473: [HxI LI Integration] Should return field values only as non-empty strings

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/HttpFileUploaderIntegrationTest.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/HttpHxInsightStorageClient.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/FileUploader.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/HttpFileUploader.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/HttpHxInsightStorageClientTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/HttpFileUploaderTest.java
[ACS-7350](https://hyland.atlassian.net/browse/ACS-7350)
[ACS-7350]: https://hyland.atlassian.net/browse/ACS-7350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ACS-7350: add logging for HttpFileUploader

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/response/ATSTransformResponseHandlerTest.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/properties/Transform.java, live-ingester/src/main/resources/application.yml
Adding empty configuration for mime type mappings. 
However, this configuration should allow to set up the mappings in following way:
``` yml
mime-type:
mapping:
'[image/png]': "image/png"
'[image/bmp]': "image/png"
'[image/gif]': "image/png"
'[image/raw]': "image/png"
'[image/*]': "image/jpeg"
'[*]': "application/pdf"
```
In the next PRs I will utilize this configuration to request transforms to mime types other than PDF (with support of exact matching, partial wildcards for subtypes and wildcards).
=> ACS-6906: Add mime type configuration for pdf transforms.

distribution/src/main/resources/docker-compose/wiremock/hxinsight/__files/presigned-urls.json, e2e-test/src/test/resources/wiremock/hxinsight/__files/pre-signed-url.json, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/response/ATSTransformResponseHandlerTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventMatchingContentMappingIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventNonMatchingContentMappingIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/MatchingContentMappingRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/NonMatchingContentMappingRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/util/ContainerSupport.java, live-ingester/src/integration-test/resources/application-test.yml, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/properties/Transform.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/bulk_ingester/IngestEventProcessor.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/HttpFileUploader.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/EventProcessor.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/MimeTypeMapper.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/RepoEventMapper.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/response/ATSTransformResponseHandler.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/content/IngestContentCommand.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/content/IngestContentCommandHandler.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/content/TriggerContentIngestionCommand.java, live-ingester/src/main/resources/application.yml, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/bulk_ingester/IngestEventProcessorTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/EventProcessorTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/MimeTypeMapperTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/RepoEventMapperTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/content/IngestContentCommandHandlerTest.java
A follow up to https://github.com/Alfresco/hxinsight-connector/pull/277
If no mime-type mapping is configured, then every content will be mapped to `application/pdf`.
If configured, mapping is done basing on following steps:
- look up exact mime-type mapping in configuration
- if above not found - look up wildcard subtype (`type/*`, e.g., `image/*`, `application/*` etc.) mapping in configuration
- if above not found - look up full wildcard mapping in configuration (`*`)
For instance, given following mapping configuration:
``` yml
mime-type:
mapping:
'[image/png]': "image/png"
'[image/bmp]': "image/png"
'[image/gif]': "image/png"
'[image/raw]': "image/png"
'[image/*]': "image/jpeg"
'[*]': "application/pdf"
```
` image/png`, `image/bmp`, `image/gif`, `image/raw` content type will request …
=> ACS-6905: Handling various mime type configurations for transforms.

live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/properties/Transform.java
We now omit the mappings by default, which causes the default mappings to be used in the `MimeTypeMapper`.
=> ACS-7450 Fix default MIME type mapping.

.secrets.baseline, common-test/src/main/java/org/alfresco/hxi_connector/common/test/docker/repository/AlfrescoRepositoryContainer.java, common-test/src/main/java/org/alfresco/hxi_connector/common/test/docker/util/DockerContainers.java, common-test/src/main/java/org/alfresco/hxi_connector/common/test/docker/util/DockerTags.java
[ACS-6826](https://hyland.atlassian.net/browse/ACS-6826)
This method is added so enterprise repository image would be downloaded when local run for test, which requires it, is performed.
[ACS-6826]: https://hyland.atlassian.net/browse/ACS-6826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ACS-6826 add method to pull enterprise repository image

prediction-applier-extension/src/main/resources/alfresco/module/alfresco-hxinsight-connector-prediction-applier-extension/model/hxi-model.xml
The property name that the prediction applies to will be stored in the child node's `cm:name` field. This will have the colon replaced by an underscore (as a colon is not valid in a name field) - e.g. `cm:description` will be `cm_description`. This matches the behaviour when creating field names in Elasticsearch.
Since there is a uniqueness check for `cm:name` then this ensures we have at most one (latest) prediction for each property.
=> ACS-6391 Add data model for HxI predictions.

.secrets.baseline, common-authentication/src/integration-test/java/org/alfresco/hxi_connector/common/adapters/auth/HxAuthenticationClientTest.java, common-authentication/src/integration-test/java/org/alfresco/hxi_connector/common/adapters/auth/util/AuthUtils.java, common-authentication/src/main/java/org/alfresco/hxi_connector/common/adapters/auth/AccessTokenProvider.java, common-authentication/src/main/java/org/alfresco/hxi_connector/common/adapters/auth/AuthenticationResult.java, common-authentication/src/main/java/org/alfresco/hxi_connector/common/adapters/auth/DefaultAccessTokenProvider.java, common-authentication/src/main/java/org/alfresco/hxi_connector/common/adapters/auth/HxAuthenticationClient.java, common-authentication/src/main/java/org/alfresco/hxi_connector/common/adapters/auth/TokenRequest.java, common-authentication/src/test/java/org/alfresco/hxi_connector/common/adapters/auth/DefaultAccessTokenProviderTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/util/E2ETestBase.java, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/adapters/auth/PredictionApplierHxAuthClientIntegrationTest.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/auth/PredictionApplierHxAuthClient.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/config/SecurityConfig.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionCollector.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/repository/NodesClient.java, prediction-applier/src/main/resources/application.yml, prediction-applier/src/test/java/org/alfresco/hxi_connector/prediction_applier/repository/NodesClientTest.java
This is a first step of refactoring authentication handling in all modules and it only concerns prediction handler authentication against ACS.
There are some parts of the code which will get changed in future PRs and I'll try to explain by commenting in this PR.
=> ACS-7605: Initial version of handling various authentication ACS methods 

prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/rest/api/PredictionChildrenRelation.java, prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/rest/api/PredictionsEntityResource.java, prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/rest/api/data_model/PredictionDataModel.java, prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/rest/api/exception/PredictionStateChangedException.java, prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/rest/api/model/PredictionModel.java, prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/rest/api/model/ReviewStatus.java, prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/service/PredictionService.java, prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/service/PredictionServiceImpl.java, prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/service/model/Prediction.java, prediction-applier-extension/src/main/resources/alfresco/module/alfresco-hxinsight-connector-prediction-applier-extension/context/service-context.xml, prediction-applier-extension/src/test/java/org/alfresco/hxi_connector/prediction_applier/service/PredictionServiceImplTest.java
PR adding new endpoint to either confirm or reject prediction for node properties.
=> [ACS-7949] Add new endpoint to confirm/reject predictions for node properties

common-authentication/src/main/java/org/alfresco/hxi_connector/common/adapters/auth/DefaultAccessTokenProvider.java, common-authentication/src/main/java/org/alfresco/hxi_connector/common/adapters/auth/HxAuthenticationClient.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/auth/LiveIngesterHxAuthClient.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/SecurityConfig.java, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionCollectorIntegrationTest.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/auth/PredictionApplierHxAuthClient.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/config/SecurityConfig.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionCollector.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/repository/NodesClient.java, prediction-applier/src/test/java/org/alfresco/hxi_connector/prediction_applier/repository/NodesClientTest.java
The second part of authentication refactoring - removes Spring Security from prediction applier.
Final part (removal of Spring Security in live ingester) will come as the next PR.
=> ACS-7605: Replacing Spring Security with custom token handling in prediction applier.

distribution/src/main/resources/docker-compose/docker-compose.yml, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionCollectorIntegrationTest.java, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/util/PredictionBufferStub.java, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/util/PredictionSourceStub.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/config/InsightPredictionsProperties.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionCollector.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionListener.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/model/prediction/Prediction.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/model/prediction/PredictionBatch.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/model/prediction/PredictionEntry.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/repository/NodesClient.java, prediction-applier/src/test/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionListenerTest.java
https://hyland.atlassian.net/browse/ACS-7586
PR contains working PoC allowing to consume actual HxI predictions API. It supports both, batches and predictions pagination.
What is required to do/fix:
- tests wasn't touched almost at all (only adjusted to models changes)
- Camel monster route should be split into smaller parts
- `quartz` route start should be delayed to run the auth first
- logging needs to be adjusted
- notifying HxI about batch status change
- probably many more
=> WIP: ACS-7586: Make code changes once prediction API is published

live-ingester/pom.xml, prediction-applier/pom.xml
As per title. Certain dependencies should be excluded when skipping tests, otherwise they won't be found at compilation time causing failures such as 
`
Error:  Failed to execute goal on project alfresco-hxinsight-connector-live-ingester: Could not resolve dependencies for project org.alfresco:alfresco-hxinsight-connector-live-ingester:jar:1.0.0-SNAPSHOT: Could not find artifact org.alfresco:alfresco-hxinsight-connector-common-authentication:jar:tests:1.0.0-SNAPSHOT in alfresco-internal (https://artifacts.alfresco.com/nexus/content/groups/internal/) -> [Help 1]
`
=> Fix compilation issues when skipping tests

.github/workflows/ci.yml
Fixing the Veracode SCA scan once again! 🤞
**Context**: the extra single quotes in [this commit](https://github.com/Alfresco/hxinsight-connector/commit/37688eb127796c432abda35fb48cd14a4a7623ac) broke it, but I guess we didn't notice as it fails silently due to the `continue-on-error` option being `true`.
**Successful run after the change**: https://github.com/Alfresco/hxinsight-connector/actions/runs/9501397929/job/26186873098?pr=405 ✅
=> Fix Veracode SCA scan

.gitignore, README.md
Also added the `distribution/src/main/resources/docker-compose/volume` to the `.gitignore` file as I don't think this is meant to be committed, yet when running the environment locally this seemed to be autogenerated and I guess we don't want people pushing their volumes by mistake.
=> Improve local development instructions

prediction-applier-extension/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/rest/api/model/QuestionSerializationTest.java, prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/rest/api/QuestionsEntityResource.java, prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/rest/api/model/Question.java
This uses the annotations from `PredictionModel` to throw an error when a request tries to set the id field.
=> ACS-8115 Differentiate between fields in request and response.

common-test/src/main/java/org/alfresco/hxi_connector/common/test/docker/repository/AlfrescoRepositoryExtension.java
This change makes it possible to run E2E tests in Windows OS.
=> ACS-8262: Fixing docker images setup to handle Windows paths

e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/UpdateNodeE2eTest.java, e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/util/client/RepositoryNodesClient.java
[ACS-6826](https://hyland.atlassian.net/browse/ACS-6826)
Upload a new version of a document and check that HxI receives the metadata update then ACS receives prediction for the node.
Added test covers scenario:
1. node is created
2. prediction is generated for the node from step 1.
3. node from step 1. is updated together with field that has prediction from step 2.
4. prediction for updated node (in step 3.) is generated but updated node should not apply this prediction and keep updated user value
[ACS-6826]: https://hyland.atlassian.net/browse/ACS-6826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ACS-6826 test to apply prediction to updated node

pom.xml
[ACS-6686](https://hyland.atlassian.net/browse/ACS-6686)
Update version for ADW and ACC so we have the latest on hxi connector
[ACS-6686]: https://hyland.atlassian.net/browse/ACS-6686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ACS-6686 update version of digital workspace and control center

.github/workflows/ci.yml
This job seems to take a reasonable amount of time, and to my knowledge none of us use the feature branch images from quay.
=> Don't push images for feature branches. [skip tests]

distribution/src/main/assemble/distribution-zip-assembly.xml
While working on implementing the SAST scan on PR, I noticed that the distribution zip did not contain all that I was expecting. In particular, it only contained the jar and license files for the `live-ingester` module.
I talked with @tpage-alfresco and he confirmed that this was not the expected result, so I went ahead and added all other jars and license files to the distribution zip. This will also be useful for the SAST scan on PR feature which I'll continue working on a separate branch.
=> Add all jars and license files to distribution zip

hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/rest/api/QuestionAnswersRelation.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/HxInsightClient.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/model/AnswerResponse.java, hxinsight-extension/src/test/java/org/alfresco/hxi_connector/hxi_extension/rest/api/QuestionAnswersRelationTest.java, hxinsight-extension/src/test/java/org/alfresco/hxi_connector/hxi_extension/service/HxInsightClientTest.java
As per https://hyland.atlassian.net/browse/ACS-8150 - the result is not yet returned by the REST API but only logged (at DEBUG level).
=> ACS-8149: Adding HxI API call to answers endpoint.

e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/UpdateNodeE2eTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/PreSignedUrlRequesterIntegrationTest.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/PreSignedUrlRequester.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/PreSignedUrlRequesterTest.java
As discussed on the daily meeting - adding user-agent header for presigned URL call.
=> ACS-8363: User-Agent header in presigned URL call

distribution/src/main/resources/docker-compose/wiremock/hxinsight/mappings/post-question.json, e2e-test/src/test/resources/wiremock/hxinsight/mappings/post-question.json, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/rest/api/QuestionsEntityResource.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/rest/api/model/QuestionModel.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/QuestionPermissionService.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/config/HxInsightClientConfig.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/model/ObjectReference.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/model/RestrictionQuery.java, hxinsight-extension/src/test/java/org/alfresco/hxi_connector/hxi_extension/service/HxInsightClientTest.java
Update to match the `submit-question` API description: http://hxai-data-platform-dev-swagger-ui.s3-website-us-east-1.amazonaws.com/?urls.primaryName=Insight%20Discovery%20API%20Draft#/Discovery-Agent-API/post_question
The main changes are to call `POST /submit-question` rather than `POST /questions` and to pass the noderefs in a set of `ObjectReference` objects.
=> ACS-8477 submit question changes

common/pom.xml, common/src/main/java/org/alfresco/hxi_connector/common/config/properties/Application.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/IntegrationProperties.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/config/InsightPredictionsProperties.java
This PR is to fix the validation that didn't work at the application startup for some properties e.g. `alfresco.repository`, `hyland-experience.storage`.
Using `@Validated` annotation results in a CGLib proxy being created for a bean so removed `final` from the `Application` class.
=> ACS-8482 Add missing @Validated annotation

.github/workflows/ci.yml
Some references to `JAVA_VERSION_SUPPORTED` were not refactored correctly.
Will most likely fix the current failure on master.
Ref: https://github.com/Alfresco/hxinsight-connector/actions/runs/10249226361/job/28352216493
=> ACS-8460 Fix CI after supported Java version refactoring

distribution/src/main/resources/docker/hxinsight-extension/java-switching-entrypoint.sh
With this fix, DC should work fine on Window OS as well.
=> NO_JIRA: Small fix in java-switching-entrypoint.sh

pom.xml
Reverting spring-boot bump (to v3.4.0) due to found vulnerability: https://github.com/Alfresco/hxinsight-connector/actions/runs/12179820334
=> NO_JIRA: reverting spring-boot bump due to found vulnerability

common-test/src/main/java/org/alfresco/hxi_connector/common/test/docker/util/DockerTags.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/DeleteRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/RequestFiltersIntegrationTest.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/DeleteNodeEventSerializer.java
https://hyland.atlassian.net/browse/CIN-885
Inside hxi connector for alfresco delete node event is not serialized as an array and because of that delete request is failing with an array body. 
Because of this issue test for delete case is failing in another pr:
https://github.com/Alfresco/hxinsight-connector/pull/767
=> [CIN-885] fix for delete event serialized issue

.github/workflows/ci.yml
https://hyland.atlassian.net/browse/CIN-1052
Disable pre_commit for schedule triggered job as Alfresco/alfresco-build-tools/.github/actions/github-list-changes action does not contain 'schedule' event name - does not supported it
=> [CIN-1052] disable pre_commit for schedule triggered job

.github/workflows/ci.yml
https://hyland.atlassian.net/browse/CIN-1052
Disable publish_snapshot_artifacts job run when scheduled nightly tests are run
=> [CIN-1052] skip publish_snapshot_artifacts job when nightly tests are run

prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/util/ContainerSupport.java
https://hyland.atlassian.net/browse/CIN-1411
Fix IllegalStateException for PredictionApplicationIntegrationTest.testPredictionApplication
=> [CIN-1411] Fix IllegalStateException

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/OpenApiRequestValidationTest.java
https://hyland.atlassian.net/browse/CIN-1802
PR to disable failing tests from OpenApiRequestValidationTest because of schema changes in /ingestion-events endpoint are not finished yet.
Tests should be enabled again after update of the OpenAPI Specification will be finished completely
=> [CIN-1802] Disable failing tests from OpenApiRequestValidationTest due to schema update

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/OpenApiRequestValidationTest.java
The schema update is now complete and the tests should start passing again.
Reverts Alfresco/hxinsight-connector#831
=> Revert "[CIN-1802] Disable failing tests from OpenApiRequestValidationTest due to schema update"

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/OpenApiRequestValidationTest.java
https://hyland.atlassian.net/browse/CIN-2513
OpenAPi tests for createOrUpdate event are disabled because swagger-request-validator-core does not support OpenAPi 3.1.1 version.
This is done to avoid CI notification about known issue.
There are still two tests that have value and still running:
testRequestToPresignedUrls()
testDeleteRequestToIngestionEvents()
Tests would change when we get permanent solution.
=> [CIN-2513] Disable failing OpenApi tests 

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventMatchingContentMappingIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventNonMatchingContentMappingIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/MatchingContentMappingRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/NonMatchingContentMappingRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/PredictionRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/RequestFiltersIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/UpdateRequestIntegrationTest.java, live-ingester/src/integration-test/resources/rest/hxinsight/requests/create-or-update-document.yml, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializer.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializerTest.java
Due to the `datetime` type not being implemented in the Ingestion API yet, we decided to remove the `datetime` type for now.
=> [CIN-2468] Remove datetime type from createdAt and modifiedAt properties

.github/workflows/nightly_tests_and_veracode.yml, .secrets.baseline
https://hyland.atlassian.net/browse/CIN-2695
${{ secrets.SRCCLR_API_TOKEN }} is not available in veracode-sca job when its triggered by the dependabot actor, same secret is available when the job runs on schedule
=> [CIN-2695] Veracode SCA fix for dependabot

.github/workflows/nightly_tests_and_veracode.yml
https://hyland.atlassian.net/browse/CIN-2695
${{ secrets.SRCCLR_API_TOKEN }} is not available in veracode-sca job when its triggered by the dependabot actor, same secret is available when the job runs on schedule
id-token: write -> fetch an OpenID Connect (OIDC) token
=> [CIN-2695] Fix for dependabot Veracode SCA

pom.xml
https://hyland.atlassian.net/browse/CIN-4066
Upgrade spring-boot version from 3.4.4. to 3.4.5 in order to upgrade transitive dependencies versions that are dependent on main spring-boot dependency
=> [CIN-4060] Bump spring-boot version from 3.4.4. to 3.4.5

live-ingester/src/integration-test/resources/rest/hxinsight/requests/create-or-update-document.yml, live-ingester/src/integration-test/resources/rest/hxinsight/requests/create-thumbnail.yml, live-ingester/src/integration-test/resources/rest/hxinsight/requests/delete-document.yml, live-ingester/src/integration-test/resources/rest/hxinsight/requests/upload-references-document.yml
ingest api v2 is now used for ingestion-events
=> feat(CIN-4141): update connector to use ingest v2 api for metadata events
