live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/event/IngestNewNodeEventHandler.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/event/UpdateNodeEventMapper.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/event/IngestNewNodeEventHandlerTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/event/UpdateNodeEventMapperTest.java
This is in preparation for adding an additional mapping to a transform request.
=> ACS-6472 Extract node event mapping.

.github/workflows/ci.yml, distribution/pom.xml, pom.xml
=> ACS-6379 Reduce default build time.

live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/SignedStorageClient.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/StorageClient.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/StorageClientIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/local/LocalStorageClient.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/local/LocalStorageConfig.java
=> ACS-6379 Move 'storage' package inside 'adapters'.

live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/DockerTags.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/DockerTagsIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/DockerTagsTest.java
=> ACS-6379 Fixed DockerTags implementation and added tests.

pom.xml
Fixed Maven build (run) warning
=> ACS-6379: Fixed Maven build (run) warning

distribution/src/main/resources/docker-compose-origin/.env, distribution/src/main/resources/docker-compose/docker-compose.yml, distribution/src/main/resources/docker-compose/init-aws.sh, distribution/src/main/resources/docker-compose/wiremock/hxinsight/__files/pre-signed-url.json, distribution/src/main/resources/docker-compose/wiremock/hxinsight/mappings/post-ingest.json, distribution/src/main/resources/docker-compose/wiremock/hxinsight/mappings/post-pre-signed-url.json, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequester.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/content/IngestContentCommandHandler.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/content/IngestContentCommandHandlerTest.java
Fixing e2e run - adding HxI mock using WireMock
For more see: https://alfresco.atlassian.net/browse/ACS-6379
=> ACS-6379: [HxI LI] S3 Credentials - PART III

distribution/src/main/resources/docker-compose/docker-compose.yml
- upgraded version to 3.8
- added healthcheck for alfresco container
- ordered container run: alfresco -> reindexer -> live-indexer
=> ACS-6379: Fix docker-compose

README.md, distribution/src/main/resources/docker-compose/docker-compose-ingesterless.yml, distribution/src/main/resources/docker-compose/docker-compose.yml, distribution/src/main/resources/docker-compose/wiremock/hxinsight/__files/pre-signed-url.json
Adding new docker-compose env without ingester service
=> ACS-6379: Adding new docker-compose env without ingester service

distribution/src/main/resources/docker-compose/docker-compose.yml
Also add debug logging for our code to d-c env.
=> ACS-6473 Fix d-c so that we can download from SFS.

distribution/src/main/resources/docker-compose/wiremock/hxinsight/__files/pre-signed-url.json, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/storage/SharedFileStoreClient.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/content/IngestContentCommandHandler.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/content/model/File.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/content/IngestContentCommandHandlerTest.java
- adding bare logic of PDF uploading
Missing stuff:
- tests
- retry logic in case of error
For more see: https://alfresco.atlassian.net/browse/ACS-6380
=> ACS-6380: [HxI LI] Upload pdf to S3 - PART I

live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeMetadataEventSerializer.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeMetadataEventSerializerTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/CreateRequestIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/DeleteRequestIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/ContainerSupport.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/RetryUtils.java
Also add E2E test for this. Currently the E2E test does not check anything about the ATS request, but we should also include that in the future.
=> ACS-6671 Fix properties format in Hx Insight request.

alfresco-formatter.xml, live-ingester/pom.xml, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequester.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/exception/EndpointClientErrorException.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/exception/EndpointServerErrorException.java, live-ingester/src/main/resources/application.yml, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequesterIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequesterTest.java
ACS-6380: [HxI LI] Upload pdf to S3 - PART II - added retry logic to PreSignedUrlRequester
=> ACS-6380: [HxI LI] added retry logic to PreSignedUrlRequester

live-ingester/pom.xml, pom.xml
These were added while trying to get the e2es working, but are not needed: https://github.com/Alfresco/hxinsight-connector/pull/95/files#r1469657862
=> Remove unused dependencies.

README.md, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/properties/Retry.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/properties/Storage.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequester.java, live-ingester/src/main/resources/application.yml, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequesterIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequesterTest.java
=> ACS-6380: adjust storage-location endpoint retry config

README.md, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/properties/Storage.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/HttpFileUploader.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequester.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/utils/ErrorUtils.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/HttpFileUploaderIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/HttpFileUploaderTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequesterIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequesterTest.java
=> ACS-6380: add retry logic to file upload

README.md, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/properties/Transform.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/storage/SharedFileStoreClient.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/storage/SharedFileStoreClientIntegrationTest.java
=> ACS-6380: retry download from sfs

README.md, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/properties/Ingester.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/out/ProducerRouteBuilder.java, live-ingester/src/main/resources/application.yml, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/out/ProducerRouteBuilderIntegrationTest.java
=> ACS-6380: [HxI LI] Upload pdf to S3 - add retry logic securing ingest request

live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/ContainerSupport.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/E2ETestBase.java
Fixed failing E2Es and enabled WireMock verbose logging
=> Fix failing E2Es

live-ingester/pom.xml, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/auth/AuthenticationService.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/auth/HxAuthenticationClient.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/SecurityConfig.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/bulk_ingester/BulkIngesterEventListener.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/HxInsightEventPublisher.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/LiveIngesterEventHandler.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/response/ATSTransformResponseHandler.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequester.java, live-ingester/src/main/resources/application.yml, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/auth/HxAuthenticationClientIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/HxInsightEventPublisherIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/storage/SharedFileStoreClientIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/HttpFileUploaderIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/storage/connector/PreSignedUrlRequesterIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/PdfOperationsIntegrationTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/AuthUtils.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/ContainerSupport.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/E2ETestBase.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/WithMockOAuth2User.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/WithMockOAuth2UserSecurityContextFactory.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/WithoutAnyUser.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/util/WithoutAnyUserSecurityContextFactory.java, pom.xml
https://alfresco.atlassian.net/browse/ACS-6649
=> ACS-6649: Authentication for HxI API - adjust endpoints and tests

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/CreateRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/RenditionTransferIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/UpdateRequestIntegrationTest.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeMetadataEventSerializer.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeMetadataEventSerializerTest.java
Note that this is technically wrong for content, but we will fix that in a future PR.
=> ACS-6929 Insert "value" before all property values.

live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/RepoEventMapper.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/property/PropertiesMapper.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/RepoEventMapperTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/mapper/property/PropertiesMapperTest.java
Suggestions were made here: https://github.com/Alfresco/hxinsight-connector/pull/198
=> ACS-6929 Rename two PropertyMapper methods as suggested in code review.

common/pom.xml, common/src/main/java/org/alfresco/hxi_connector/common/repository/filter/AspectFilter.java, common/src/main/java/org/alfresco/hxi_connector/common/repository/filter/TypeFilter.java, common/src/test/java/org/alfresco/hxi_connector/common/repository/filter/AspectFilterTest.java, common/src/test/java/org/alfresco/hxi_connector/common/repository/filter/TypeFilterTest.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/LiveIngesterEventHandler.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/AspectFilterApplier.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/RepoEventFilterApplier.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/RepoEventFilterHandler.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/TypeFilterApplier.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/AspectFilterApplierTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/RepoEventFilterHandlerTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/TypeFilterApplierTest.java
Moving filtering logic to common module as it will be used in bulk ingester.
=> ACS-6874: Moving filters logic to common module.

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/CreateRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/RenditionTransferIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/RequestFiltersIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/UpdateRequestIntegrationTest.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializer.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializerTest.java
The list can contain a single entry though.
=> ACS-7345 Hx Insight always expects a list of ingestion events.

live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/HttpFileUploader.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/HttpFileUploaderTest.java
https://alfresco.atlassian.net/browse/ACS-7350
=> ACS-7350: Failed to upload pdf rendition to presigned url

live-ingester/pom.xml, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/util/ContainerSupport.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/HttpHxInsightStorageClient.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/HttpFileUploader.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/PreSignedUrlRequester.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/response/ATSTransformResponseHandler.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/storage/SharedFileStoreClient.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/ports/ingestion_engine/storage/model/IngestContentResponse.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/content/IngestContentCommandHandler.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/HttpHxInsightStorageClientTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/HttpFileUploaderTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/content/IngestContentCommandHandlerTest.java, pom.xml
- fixed issue while sending multipart request
- fixed logging a bit
https://hyland.atlassian.net/browse/ACS-7350?focusedCommentId=1220024
=> ACS-7350: Failed to upload pdf rendition to presigned url fix

common/src/main/java/org/alfresco/hxi_connector/common/exception/EndpointClientErrorException.java, common/src/main/java/org/alfresco/hxi_connector/common/exception/EndpointServerErrorException.java, common/src/main/java/org/alfresco/hxi_connector/common/exception/HxInsightConnectorRuntimeException.java, common/src/main/java/org/alfresco/hxi_connector/common/exception/ResourceNotFoundException.java, common/src/main/java/org/alfresco/hxi_connector/common/util/ErrorUtils.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/adapters/auth/HxAuthenticationClientIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/HxInsightEventPublisherIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/HttpFileUploaderIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/PreSignedUrlRequesterIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/response/ATSTransformResponseHandlerTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/storage/SharedFileStoreClientIntegrationTest.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/auth/HxAuthenticationClient.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/properties/Retry.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/HxInsightEventPublisher.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/HttpFileUploader.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/PreSignedUrlRequester.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/response/ATSTransformResponseHandler.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/transform/storage/SharedFileStoreClient.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/HttpFileUploaderTest.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/hx_insight/storage/connector/PreSignedUrlRequesterTest.java
https://hyland.atlassian.net/browse/ACS-6390
=> ACS-6390: Refactoring - moved error handling to common module

common/pom.xml, common/src/main/java/org/alfresco/hxi_connector/common/exception/EndpointClientErrorException.java, common/src/main/java/org/alfresco/hxi_connector/common/exception/EndpointServerErrorException.java, common/src/main/java/org/alfresco/hxi_connector/common/exception/HxInsightConnectorRuntimeException.java, common/src/main/java/org/alfresco/hxi_connector/common/exception/ResourceNotFoundException.java, common/src/main/java/org/alfresco/hxi_connector/common/model/prediction/Prediction.java, common/src/main/java/org/alfresco/hxi_connector/common/model/repository/Node.java, common/src/main/java/org/alfresco/hxi_connector/common/model/repository/NodeEntry.java, common/src/main/java/org/alfresco/hxi_connector/common/util/ErrorUtils.java, prediction-applier-extension/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/util/client/AspectsClient.java, prediction-applier/pom.xml, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/hxinsight/PredictionListenerIntegrationTest.java, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/repository/NodesClientIntegrationTest.java, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/util/local/LocalSqsPublisher.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/exception/PredictionApplierRuntimeException.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/hxinsight/PredictionListener.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/hxinsight/PredictionMapper.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/repository/NodesClient.java, prediction-applier/src/main/resources/application.yml
https://hyland.atlassian.net/browse/ACS-6390
=> ACS-6390: [HxI PH] Update Repo with predictions

distribution/src/main/resources/docker-compose/docker-compose.yml
Also double the memory allocation for Share (since this occasionally crashes for me with OOM).
=> ACS-7450 Assign more memory to transform-core to prepare for 4k image transforms from the bulk ingester.

common-authentication/src/main/java/org/alfresco/hxi_connector/common/adapters/auth/AuthSupport.java, distribution/src/main/resources/docker-compose/docker-compose.yml, distribution/src/main/resources/docker-compose/init-aws.sh, prediction-applier/pom.xml, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionCollectorIntegrationTest.java, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/util/PredictionBufferStub.java, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/util/PredictionTriggerStub.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/config/InsightPredictionsProperties.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionCollector.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionListener.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionMapper.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/util/LinkedListJacksonDataFormat.java, prediction-applier/src/main/resources/application.yml, prediction-applier/src/test/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionListenerTest.java
PR also includes refactoring around predictions collecting.
Jira task: https://hyland.atlassian.net/browse/ACS-7545
=> ACS-7545: [HxI PH] Read predictions from AMQ rather than SQS

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/PredictionRequestIntegrationTest.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/EventProcessor.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/util/EventUtils.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/EventProcessorTest.java
https://hyland.atlassian.net/browse/ACS-6393
=> ACS-6393: [HxI PH] Feedback protection in Live Ingester

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/PredictionRequestIntegrationTest.java
Also updated events in some existing tests to be more realistic.
=> ACS-7708 Add E2E for confirmation reinforcement.

e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/CreateNodeE2eTest.java, e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/UpdateNodeE2eTest.java, e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/util/client/RepositoryNodesClient.java, e2e-test/src/test/resources/wiremock/hxinsight/__files/presigned-urls.json, e2e-test/src/test/resources/wiremock/hxinsight/mappings/get-prediction-batches-empty-list.json, e2e-test/src/test/resources/wiremock/hxinsight/mappings/get-prediction-batches-first-page.json, e2e-test/src/test/resources/wiremock/hxinsight/mappings/get-predictions-empty-list.json, e2e-test/src/test/resources/wiremock/hxinsight/mappings/put-prediction-batch.json
https://hyland.atlassian.net/browse/ACS-7742
=> ACS-7742: Reinstate UpdateNodeE2eTest

e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/UpdateNodeE2eTest.java
https://hyland.atlassian.net/browse/ACS-7903
=> ACS-7903: [HxI PH] Feedback protection in Live Ingester - E2E tests

prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/rest/api/AgentsEntityResource.java, prediction-applier-extension/src/main/java/org/alfresco/hxi_connector/prediction_applier/rest/api/model/Agent.java, prediction-applier-extension/src/test/java/org/alfresco/hxi_connector/prediction_applier/rest/api/model/AgentDeserializationTest.java
Currently stubbed with an empty list response.
=> ACS-8137 REST endpoint to list available AI agents.

e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/DeleteNodeE2eTest.java, e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/util/client/RepositoryNodesClient.java
[ACS-6826](https://hyland.atlassian.net/browse/ACS-6826)
Test where node is deleted on ACS and delete event is sent to HxI
[ACS-6826]: https://hyland.atlassian.net/browse/ACS-6826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ACS-6826 adding test for delete event

hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/rest/api/model/QuestionModel.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/model/Question.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/model/QuestionResponse.java
These aren't currently doing anything and the validation will be performed by HxI anyway.
=> ACS-8139 Remove validation from JAMP objects.

hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/rest/api/AvatarRelation.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/rest/api/exception/AgentAvatarException.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/config/HxInsightClientConfig.java, hxinsight-extension/src/main/resources/alfresco/module/alfresco-hxinsight-connector-hxinsight-extension/context/service-context.xml, hxinsight-extension/src/test/java/org/alfresco/hxi_connector/hxi_extension/rest/api/AvatarRelationTest.java
=> ACS-8351 Create agents avatar endpoint with mocked response.

common/pom.xml, common/src/main/java/org/alfresco/hxi_connector/common/model/ingest/IngestEvent.java, common/src/main/java/org/alfresco/hxi_connector/common/util/ErrorUtils.java
https://hyland.atlassian.net/browse/ACS-8454
=> ACS-8454: Add support for Java 11 - common module

hxinsight-extension/pom.xml
Without this IntelliJ refuses to run tests in HxClientTest for me.
=> ACS-8440 Remove test dependency on vaadin json library.

hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/rest/api/QuestionsEntityResource.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/rest/api/model/QuestionModel.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/rest/api/model/RetryModel.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/HxInsightClient.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/model/RestrictionQuery.java, hxinsight-extension/src/test/java/org/alfresco/hxi_connector/hxi_extension/rest/api/model/RetryModelSerializationTest.java, hxinsight-extension/src/test/java/org/alfresco/hxi_connector/hxi_extension/service/HxInsightClientTest.java
Also fix for feedback endpoint to add default constructor.
=> ACS-8440 Retry endpoint.

distribution/src/main/resources/docker-compose/wiremock/hxinsight/__files/agents.json, e2e-test/src/test/resources/wiremock/hxinsight/mappings/get-agents.json, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/rest/api/model/AgentModel.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/model/Agent.java, hxinsight-extension/src/test/java/org/alfresco/hxi_connector/hxi_extension/service/HxInsightClientTest.java
Changes related to return from `GET /agent`
=> ACS-8482 Adapt the Agents API to recent changes

common-test/src/main/java/org/alfresco/hxi_connector/common/test/docker/util/DockerContainers.java, common-test/src/main/java/org/alfresco/hxi_connector/common/test/util/RetryUtils.java, e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/BulkIngesterE2eTest.java, e2e-test/src/test/resources/data/alfresco-dump.sql, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/metadata/property/CategoryPropertyResolver.java
imo we should invent some good test cases for bulk ingester and include them in this test (but under separate story)
=> ACS-8165: add bulk ingester ACL e2e test

common-authentication/src/main/java/org/alfresco/hxi_connector/common/adapters/auth/AuthService.java
https://hyland.atlassian.net/browse/ACS-8417
=> ACS-8417: Change hxai-environment to hxp-environment

common-test/src/main/java/org/alfresco/hxi_connector/common/test/docker/repository/AlfrescoRepositoryContainer.java, common-test/src/main/java/org/alfresco/hxi_connector/common/test/docker/util/DockerContainers.java, e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/UpdateNodeE2eTest.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/hx_insight/PredictionListener.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/model/repository/PredictionModelResponse.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/repository/NodesClient.java, prediction-applier/src/test/java/org/alfresco/hxi_connector/prediction_applier/repository/NodesClientTest.java
https://hyland.atlassian.net/browse/ACS-8513
=> ACS-8513: Fix intermittently failing UpdateNodeE2eTest

live-ingester/pom.xml, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/LiveIngesterApplication.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/AuthConfig.java, live-ingester/src/main/resources/application.yml
https://hyland.atlassian.net/browse/ACS-8607
=> ACS-8607: Create Helm chart for live-ingester - adding liveness probe endpoint

hxinsight-extension/src/main/resources/alfresco/module/alfresco-hxinsight-connector-hxinsight-extension/alfresco-global.properties, live-ingester/src/main/resources/application.yml, prediction-applier/src/main/resources/application.yml
https://hyland.atlassian.net/browse/ACS-8570
=> ACS-8570: Adjust auth grant-type

common-test/src/main/java/org/alfresco/hxi_connector/common/test/docker/util/DockerContainers.java, distribution/src/main/resources/docker-compose/docker-compose-minimal.yml, distribution/src/main/resources/docker-compose/docker-compose-w-keycloak.yml, distribution/src/main/resources/docker-compose/docker-compose.yml, e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/AgentsE2eTest.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/HxInsightClient.java, hxinsight-extension/src/main/java/org/alfresco/hxi_connector/hxi_extension/service/config/HxInsightClientConfig.java, hxinsight-extension/src/main/resources/alfresco/module/alfresco-hxinsight-connector-hxinsight-extension/alfresco-global.properties, hxinsight-extension/src/main/resources/alfresco/module/alfresco-hxinsight-connector-hxinsight-extension/context/service-context.xml, hxinsight-extension/src/test/java/org/alfresco/hxi_connector/hxi_extension/service/HxInsightClientTest.java
https://hyland.atlassian.net/browse/ACS-8631
=> ACS-8631: Adjust configuration to different endpoints for agents and questions APIs

distribution/src/main/resources/docker-compose/wiremock/hxinsight/__files/answer.json
[ACS-8681](https://hyland.atlassian.net/browse/ACS-8681)
Update wiremock response for the answer call by changing questionId to question 
[ACS-8681]: https://hyland.atlassian.net/browse/ACS-8681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ACS-8681] adjust wiremock response for the answer call

distribution/src/main/resources/docker-compose/docker-compose.yml, e2e-test/src/test/java/org/alfresco/hxi_connector/e2e_test/UpdateNodeE2eTest.java, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/util/ContainerSupport.java, prediction-applier/src/main/java/org/alfresco/hxi_connector/prediction_applier/repository/NodesClient.java, prediction-applier/src/main/resources/application.yml
=> ACS-8609: Add prediction-applier component to alfresco-connector-hxi Helm chart

.github/workflows/ci.yml, distribution/src/main/resources/docker/hxinsight-extension/Dockerfile, scripts/ci/buildDockerImages.sh, scripts/ci/cleanup_cache.sh, scripts/ci/releaseDockerImage.sh
Also made some cleanup of shell scripts
=> NO_JIRA: fix docker build issue

common-authentication/src/integration-test/java/org/alfresco/hxi_connector/common/adapters/auth/DefaultAuthenticationClientTest.java, common-authentication/src/main/java/org/alfresco/hxi_connector/common/adapters/auth/DefaultAuthenticationClient.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/adapters/auth/LiveIngesterAuthClientIntegrationTest.java, prediction-applier/src/integration-test/java/org/alfresco/hxi_connector/prediction_applier/adapters/auth/PredictionApplierAuthClientIntegrationTest.java
https://hyland.atlassian.net/browse/ACS-8753
=> ACS-8753: Log meaningful message in case of Auth error

live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventMatchingContentMappingIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/bulk_ingester/BulkIngesterEventNonMatchingContentMappingIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/CreateRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/DeleteRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/MatchingContentMappingRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/NonMatchingContentMappingRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/OpenApiRequestValidationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/PredictionRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/RenditionTransferIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/RequestFiltersIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/UpdateRequestIntegrationTest.java, live-ingester/src/integration-test/resources/rest/hxinsight/requests/create-document.yml, live-ingester/src/integration-test/resources/rest/hxinsight/requests/update-document.yml, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializer.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializerTest.java
Changes based on: https://hyland.atlassian.net/wiki/spaces/HxAI/pages/1613038747/Standardized+Metadata+Properties+for+Insight
https://hyland.atlassian.net/browse/CIN-1399
=> add metadata properties to ingest requests

.secrets.baseline, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/util/ContentUtils.java, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/util/DigestIdentifierParams.java, live-ingester/src/main/resources/application.yml, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/util/ContentUtilsTest.java
=> CIN-303 Add content digest identifier algorithm

.github/workflows/ci.yml
https://hyland.atlassian.net/browse/CIN-2085
=> CIN-2085: bump ACS repo version in CI tests

.github/workflows/nightly_tests_and_veracode.yml
https://hyland.atlassian.net/browse/CIN-2358
=> [CIN-2358] Fix build for nightly tests job

live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializer.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializerTest.java
=> [CIN-2018] Add new test cases to check data types with non annotated properties

distribution/src/main/resources/docker-compose/docker-compose.yml, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/CreateRequestIntegrationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/OpenApiTckRequestValidationTest.java, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/UpdateRequestIntegrationTest.java, live-ingester/src/integration-test/resources/rest/hxinsight/requests/create-thumbnail.yml, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializer.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializerTest.java
For example the standard property cm:contentPropertyName.
=> CIN-2773 Handle object properties.

.github/workflows/ci.yml
https://hyland.atlassian.net/browse/CIN-3285
Pass GitHub token into tck test action
=> [CIN-3285] Update TCK before release job

.github/workflows/nightly_tests_and_veracode.yml, live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/UpdateRequestIntegrationTest.java, live-ingester/src/integration-test/resources/rest/hxinsight/requests/create-thumbnail.yml, live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializer.java, live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/config/jackson/UpdateNodeEventSerializerTest.java
https://hyland.atlassian.net/browse/CIN-3356
The object data types should be plain JSON objects.
testCreateThumbnailEvents() is expected to file till Ingestion HxI side will not merge their changes.
nightly_tests job is triggered only for monitoring in the PR
=> [CIN-3356] Initial implementation of loose object type schema

.github/workflows/ci.yml
https://hyland.atlassian.net/browse/CIN-4238
=> [CIN-4238] [release] 2.0.3-A.1

.github/workflows/ci.yml
https://hyland.atlassian.net/browse/CIN-4503
=> [CIN-4503] [release] 2.0.3-A.2

.github/workflows/ci.yml
https://hyland.atlassian.net/browse/CIN-4521
Skip private and test dependency scope
=> [CIN-4521] Set scope for dependency graph of GHAS

.github/workflows/ci.yml, scripts/ci/processCoverageReport.py
After implementing the Python script, the mechanism of checking and generating code coverage is to check the code coverage and if the overall coverage falls below 80% or the coverage of new files or new code falls below 80%, a comment with details will be uploaded. Additionally, comments are not added every time, but updated. If code coverage threshold is greater than 80% comment will be not uploaded. If the coverage of new code falls below 80%, the next step "Enforce minimum code coverage threshold on changed files" in CI will not pass.
=> feat(CIN-4547): replace jacoco-report with our python script

.github/workflows/ci.yml
https://hyland.atlassian.net/browse/CIN-5613
=> [CIN-5613] [release] 2.0.3-A.4
